### ISSUE TITLE
Base below 1 no longer allowed (for usage with rems)

### ISSUE THREAD

**Issue by felixfbecker** [darwintantuco/stylelint-8-point-grid#23]
We use `rem` in our codebase instead of `px`, which has a lot of benefits. To illustrate, `1rem` equals `16px` at a `16px` root font size. To align with the 8pt grid, we therefor need to use e.g. a base of `0.5` to make sure every `rem` value is divisible by `0.5`, i.e. `0.5rem`=`8px`, `1rem`=`16px`, `1.5rem`=`24px` etc. If we want, we can use a different `font-size` between the marketing page and the application and the grid and stylelint config will scale automatically.

This was possible in 0.2.4, but 0.2.5 enforced that `base` _must_ be a multiple of `1`, breaking this use case. Is there a reason for that requirement?

https://github.com/darwintantuco/stylelint-8-point-grid/blob/bf3ab78bd6cd347074c73119ca8b8ec6e91f33c8/src/utils.ts#L3:14

**Comment by darwintantuco** [comment]
Interesting! haven't thought of it use case. I agree, let me see what I can do.

**Comment by felixfbecker** [comment]
There seems to be more to this, actually. Apparently `rem` values are not checked at all, only `px` values

**Comment by darwintantuco** [comment]
yeah, that's correct. currently, it only checks px values.
thanks for the PR! will check

**Comment by darwintantuco** [comment]
awesome work!
I'll try to finish #22 tomorrow and can probably release new version on Friday.

**Comment by darwintantuco** [comment]
I might tweak the api soon, maybe separate px base from rem base? not yet sure
I just realized if you're using the default config (base: 8)
it will require rem values to be divisible by 8 as well

**Comment by felixfbecker** [comment]
Personally not bothered by that because we just forbid usage of `px` with another rule. You could define separate ones, but it would require knowledge of the root font size.

**Comment by felixfbecker** [comment]
Personally it would be awesome for me if we could maybe get #25 released before the other changes because I don't know if I'll have time after this week to work on adopting the rule 🙂

**Comment by darwintantuco** [comment]
@felixfbecker done! just published v1.0.0
let me know if it works well

**Comment by darwintantuco** [comment]
looking back, I'm thinking of some improvements, especially handling rem values better
off the top of my head, we can compute rem base from base,
having base 8 will also check if rem values are divisible by 0.5

**Comment by darwintantuco** [comment]
done with the improvements (v2.1.0)
let me know what you think 😄
