### ISSUE TITLE
Add the feature to add custom properties

### ISSUE THREAD

**Issue by max-norin** [darwintantuco/stylelint-8-point-grid#28]
You can use `PostCSS` to add custom properties. This plugin can't check custom properties. For example `size` properties in [postcss-short](https://github.com/jonathantneal/postcss-short). You also don't have any logical CSS properties: `margin-block`, `margin-block-start`, `margin-block-end`, `margin-inline`, `margin-inline-start`, `margin-inline-end`, `margin-start`, `margin-end` and etc.

**Comment by darwintantuco** [comment]
will check this out when I have the time

**Comment by darwintantuco** [comment]
Interesting! first time seeing postcss-short and I agree, it's a perfect use case of adding custom properties.

**Comment by darwintantuco** [comment]
I'm not familiar with logical CSS properties, will check it out.

**Comment by darwintantuco** [comment]
apologies for the radio silence, totally forget about this

initial PRs: 
- https://github.com/darwintantuco/stylelint-8-point-grid/pull/39
- https://github.com/darwintantuco/stylelint-8-point-grid/pull/40
