### ISSUE TITLE
Add support for CSS Logical Properties

### ISSUE THREAD

**Issue by kcastellino** [darwintantuco/stylelint-8-point-grid#38]
Hi,

Adding support for CSS Logical Properties was previously mentioned in issue #28, but I feel a separate tracking issue is warranted, as logical properties are well-defined and widely supported, and the scope of that issue is much larger. Logical properties allow for spacing and layout to automatically adjust based on the writing system, and the number of logical properties (such as `padding-inline-start` and `margin-block-end`, which for English pages correspond to `padding-left` and `margin-bottom`) is similar to the exisiting number of positional properties.

The simplest option would be to add the logical properties corresponding to supported physical properties to the `supportedCssProperties` array. If you like, I'd be happy to write up a pull request with the modifications and tests. Otherwise, let me know if you need more info.

**Comment by darwintantuco** [comment]
thank you for creating an issue, I totally forgot about this

initial PR: https://github.com/darwintantuco/stylelint-8-point-grid/pull/39

**Comment by darwintantuco** [comment]
I haven't used css logical properties yet, it's possible I missed some properties 😅

**Comment by kcastellino** [comment]
Yep, looks like you covered them all!
